apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: euvoice-platform
    releaseName: euvoice
    namespace: voiquyr
    version: 0.1.0
    path: ../../helm/euvoice-platform
    valuesFile: ../../helm/euvoice-platform/values.yaml
