apiVersion: v1
kind: Namespace
metadata:
  name: voiquyr
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    compliance.euvoice.ai/region: frankfurt
    compliance.euvoice.ai/jurisdiction: eu
